---
- name: set root shell
  user:
    name: root
    shell: /bin/bash
  become: true
  
- name: set root bash prompt and ls aliases
  blockinfile:
    path: /root/.bashrc
    create: yes
    owner: root
    group: root
    mode: '0600'
    block: |
      export PS1='{{ prompts.root }}'
      
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'
  become: true
  
- name: set root vimrc config
  lineinfile:
    path: /root/.vimrc
    create: yes
    owner: root
    group: root
    mode: '0600'
    line: set mouse-=a
  become: true
  
- name: set root password
  user:
    name: "root"
    password: "{{ root_password | password_hash('sha512', password_salt | default('')) }}"
  when: root_password is defined
  become: true
  
- name: create work_users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: "{{ work_users }}"
  become: true
  
- name: set work_users bash prompt and ls aliases
  blockinfile:
    path: "/home/{{ item.name }}/.bashrc"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
    block: |
      export PS1='{{ prompts.user }}'
      
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'
  with_items: "{{ work_users }}"
  become: true
  
- name: set work_users vimrc config
  lineinfile:
    path: "/home/{{ item.name }}/.vimrc"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
    line: set mouse-=a
  with_items: "{{ work_users }}"
  become: true
    
- name: set work_users password
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512', password_salt | default('')) }}"
  when: item.password is defined
  with_items: "{{ work_users }}"
  become: true
  
